### ISSUE TITLE
sqlite3 未找到模块

### ISSUE THREAD

**Issue by ShiinaMono** [dcyuki/yumemi_bot#1]
[root@VM-4-17-centos yumemi_bot]# npm start

> yumemi_bot@0.6.1 start /root/bot/yumemi_bot
> node ./dist/index.js

--------------------------------------------------------------------------------------------
                                                                             _         
      \    / _  | |  _  _  ._ _   _    _|_  _    \_/    ._ _   _  ._ _  o   |_)  _ _|_ 
       \/\/ (/_ | | (_ (_) | | | (/_    |_ (_)    | |_| | | | (/_ | | | |   |_) (_) |_ 

--------------------------------------------------------------------------------------------
[2021-08-26T22:09:43.268] [MARK] [yumemi bot log] - ----------
[2021-08-26T22:09:43.269] [MARK] [yumemi bot log] - Package Version: yumemi_bot@0.6.1 (Released on 2021/7/25)
[2021-08-26T22:09:43.269] [MARK] [yumemi bot log] - View Changelogs：https://docs.yumemi.moe/#/changelog/
[2021-08-26T22:09:43.269] [MARK] [yumemi bot log] - ----------
(node:523316) UnhandledPromiseRejectionWarning: Error: Cannot find module '/root/bot/yumemi_bot/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /root/bot/yumemi_bot/node_modules/sqlite3/lib/sqlite3-binding.js
- /root/bot/yumemi_bot/node_modules/sqlite3/lib/sqlite3.js
- /root/bot/yumemi_bot/dist/sqlite.js
- /root/bot/yumemi_bot/services/web/router/api.js
- /root/bot/yumemi_bot/services/web/router/index.js
- /root/bot/yumemi_bot/services/web/index.js
- /root/bot/yumemi_bot/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/bot/yumemi_bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:523316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:523316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-08-26T22:09:43.431] [WARN] [yumemi bot log] - Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /root/bot/yumemi_bot/node_modules/sharp/lib/constructor.js
- /root/bot/yumemi_bot/node_modules/sharp/lib/index.js
- /root/bot/yumemi_bot/plugins/guess/index.js
- /root/bot/yumemi_bot/dist/plugin.js
- /root/bot/yumemi_bot/dist/index.js

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/root/bot/yumemi_bot/node_modules/sharp/lib/constructor.js:32:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/bot/yumemi_bot/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

看不懂，泪目🤣🤣

**Comment by xueelf** [comment]
> [root@VM-4-17-centos yumemi_bot]# npm start
> 
> > yumemi_bot@0.6.1 start /root/bot/yumemi_bot
> > node ./dist/index.js
> 
> ```
>                                                                          _         
>   \    / _  | |  _  _  ._ _   _    _|_  _    \_/    ._ _   _  ._ _  o   |_)  _ _|_ 
>    \/\/ (/_ | | (_ (_) | | | (/_    |_ (_)    | |_| | | | (/_ | | | |   |_) (_) |_ 
> ```
> 
> [2021-08-26T22:09:43.268] [MARK] [yumemi bot log] - ----------
> [2021-08-26T22:09:43.269] [MARK] [yumemi bot log] - Package Version: yumemi_bot@0.6.1 (Released on 2021/7/25)
> [2021-08-26T22:09:43.269] [MARK] [yumemi bot log] - View Changelogs：https://docs.yumemi.moe/#/changelog/
> [2021-08-26T22:09:43.269] [MARK] [yumemi bot log] - ----------
> (node:523316) UnhandledPromiseRejectionWarning: Error: Cannot find module '/root/bot/yumemi_bot/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
> Require stack:
> 
> * /root/bot/yumemi_bot/node_modules/sqlite3/lib/sqlite3-binding.js
> * /root/bot/yumemi_bot/node_modules/sqlite3/lib/sqlite3.js
> * /root/bot/yumemi_bot/dist/sqlite.js
> * /root/bot/yumemi_bot/services/web/router/api.js
> * /root/bot/yumemi_bot/services/web/router/index.js
> * /root/bot/yumemi_bot/services/web/index.js
> * /root/bot/yumemi_bot/dist/index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   at require (internal/modules/cjs/helpers.js:92:18)
>   at Object. (/root/bot/yumemi_bot/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>   at Module.load (internal/modules/cjs/loader.js:937:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   (Use `node --trace-warnings ...` to show where the warning was created)
>   (node:523316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>   (node:523316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>   [2021-08-26T22:09:43.431] [WARN] [yumemi bot log] - Error:
>   Something went wrong installing the "sharp" module
> 
> Cannot find module '../build/Release/sharp.node'
> Require stack:
> 
> * /root/bot/yumemi_bot/node_modules/sharp/lib/constructor.js
> * /root/bot/yumemi_bot/node_modules/sharp/lib/index.js
> * /root/bot/yumemi_bot/plugins/guess/index.js
> * /root/bot/yumemi_bot/dist/plugin.js
> * /root/bot/yumemi_bot/dist/index.js
> * Remove the "node_modules/sharp" directory then run
>   "npm install --ignore-scripts=false --verbose sharp" and look for errors
> * Consult the installation documentation at https://sharp.pixelplumbing.com/install
> * Search for this error at https://github.com/lovell/sharp/issues
>   at Object. (/root/bot/yumemi_bot/node_modules/sharp/lib/constructor.js:32:9)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>   at Module.load (internal/modules/cjs/loader.js:937:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   at require (internal/modules/cjs/helpers.js:92:18)
>   at Object. (/root/bot/yumemi_bot/node_modules/sharp/lib/index.js:3:15)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 
> 看不懂，泪目🤣🤣

Cannot find module node_sqlite3 ，sqlite3 的 npm 包没装上，可以重新 `npm i` 一遍看看，如果网络环境不好可以尝试使用 cnpm 下载或者更换国内镜像源

**Comment by ShiinaMono** [comment]
使用cnpm i `安装的时候似乎有些问题`
`✔ Run 2 scripts
anti semver @types/sqlite3@3.1.7 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
anti semver bili-api@1.6.0 › got@10.7.0 › @types/cacheable-request@6.0.2 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
anti semver bili-api@1.6.0 › got@10.7.0 › @types/cacheable-request@6.0.2 › @types/keyv@3.1.2 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
anti semver bili-api@1.6.0 › got@10.7.0 › @types/cacheable-request@6.0.2 › @types/responselike@1.0.0 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
deprecate sqlite3@5.0.2 › node-pre-gyp@^0.11.0 Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
deprecate sqlite3@5.0.2 › node-gyp@3.8.0 › request@^2.87.0 request has been deprecated, see https://github.com/request/request/issues/3142
deprecate sqlite3@5.0.2 › node-gyp@3.8.0 › tar@^2.0.0 This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
deprecate sqlite3@5.0.2 › node-gyp@3.8.0 › request@2.88.2 › har-validator@~5.1.3 this library is no longer supported
Recently updated (since 2021-08-21): 4 packages (detail see file /root/bot/yumemi_bot/node_modules/.recently_updates.txt)
✔ All packages installed (281 packages installed from npm registry, used 5s(network 4s), speed 161.05KB/s, json 254(616.33KB), tarball 0B)`

**Comment by JMFANS** [comment]
登陆报错
`> yumemi_bot@0.6.1 start /root/bot/yumemi_bot
> node ./dist/index.js

--------------------------------------------------------------------------------------------
                                                                             _         
      \    / _  | |  _  _  ._ _   _    _|_  _    \_/    ._ _   _  ._ _  o   |_)  _ _|_ 
       \/\/ (/_ | | (_ (_) | | | (/_    |_ (_)    | |_| | | | (/_ | | | |   |_) (_) |_ 

--------------------------------------------------------------------------------------------
[2021-08-28T11:42:39.343] [MARK] [yumemi bot log] - ----------
[2021-08-28T11:42:39.344] [MARK] [yumemi bot log] - Package Version: yumemi_bot@0.6.1 (Released on 2021/7/25)
[2021-08-28T11:42:39.344] [MARK] [yumemi bot log] - View Changelogs：https://docs.yumemi.moe/#/changelog/
[2021-08-28T11:42:39.344] [MARK] [yumemi bot log] - ----------
[2021-08-28T11:42:39.533] [MARK] [iPad:3258667130] - ----------
[2021-08-28T11:42:39.533] [MARK] [iPad:3258667130] - Package Version: oicq@1.19.5 (Released on 2021/8/23)
[2021-08-28T11:42:39.533] [MARK] [iPad:3258667130] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-08-28T11:42:39.533] [MARK] [iPad:3258667130] - ----------
[2021-08-28T11:42:39.535] [MARK] [iPad:3258667130] - 正在登录账号 bot ...
[2021-08-28T11:42:39.535] [MARK] [iPad:3258667130] - 首次登录请输入密码：
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at Application.listen (/root/bot/yumemi_bot/node_modules/_koa@2.13.1@koa/lib/application.js:82:19)
    at /root/bot/yumemi_bot/services/web/index.js:20:9
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1347:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 80
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yumemi_bot@0.6.1 start: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yumemi_bot@0.6.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-28T03_42_39_612Z-debug.log
You have new mail in /var/spool/mail/root`

**Comment by xueelf** [comment]
> 使用cnpm i `安装的时候似乎有些问题`
> `✔ Run 2 scripts
> anti semver @types/sqlite3@3.1.7 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
> anti semver bili-api@1.6.0 › got@10.7.0 › @types/cacheable-request@6.0.2 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
> anti semver bili-api@1.6.0 › got@10.7.0 › @types/cacheable-request@6.0.2 › @types/keyv@3.1.2 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
> anti semver bili-api@1.6.0 › got@10.7.0 › @types/cacheable-request@6.0.2 › @types/responselike@1.0.0 › @types/node@* delcares @types/node@*(resolved as 16.7.4) but using ancestor(root package.json)'s dependency @types/node@^15.12.5(resolved as 15.14.9)
> deprecate sqlite3@5.0.2 › node-pre-gyp@^0.11.0 Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> deprecate sqlite3@5.0.2 › node-gyp@3.8.0 › request@^2.87.0 request has been deprecated, see https://github.com/request/request/issues/3142
> deprecate sqlite3@5.0.2 › node-gyp@3.8.0 › tar@^2.0.0 This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
> deprecate sqlite3@5.0.2 › node-gyp@3.8.0 › request@2.88.2 › har-validator@~5.1.3 this library is no longer supported
> Recently updated (since 2021-08-21): 4 packages (detail see file /root/bot/yumemi_bot/node_modules/.recently_updates.txt)
> ✔ All packages installed (281 packages installed from npm registry, used 5s(network 4s), speed 161.05KB/s, json 254(616.33KB), tarball 0B)`

All packages installed. 有什么问题？

**Comment by ShiinaMono** [comment]
估计就是版本不是最新吧
This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
可以正常使用
